services:
  rent-hunter:
    image: knotatypo/rent-finder
    container_name: rent-hunter
    ports:
      - "4321:4321"
    environment:
      GEOCODE_API_KEY:
      DB_USER:
      DB_PASS:
      DB_HOST:
      S3_ENDPOINT_URL:
      S3_KEY_ID:
      S3_ACCESS_KEY:
      TZ: Brisbane/Australia